GLOBAL:
  NAME: ffpwcnet-chairs-lr1e-4_1200k
  MIXED_PRECISION: false

  SEED: 1234
  CUDNN_ENABLED: true
  ALLOW_TF32: true
  NUM_THREADS: 16
  NUM_WORKERS: 16


TRAIN:
  STAGE: chairs
  
  PRETRAIN: 
  RESTORE_CHECKPOINT: 
  ADD_NOISE: true

  NUM_STEPS: 1200000
  BATCH_SIZE: 8
  IMAGE_SIZE: [368, 496]

  SEPARATE_LR: false

  LOSS_TYPE: MixLoss
  MASK_TYPE: sift

  MASK_MODAL: point
  MASK_CHANNEL: 3
  MASK_DILATE: 31
  
  KERNEL_SIZE: 31
  KERNEL_SIGMA: 5

  CLIP: 1.0

  MAX_FLOW: 400
  LOSS_MODE: pretrain
  LOSS_WEIGHTS: [0.005, 0.01, 0.02, 0.08, 0.32]
  LOSS_Q:
  LOSS_EPSILON:
  LOSS_KERNEL_SIZE: 1
  LOSS_SIGMA: 0.01
  LOSS_LAMDA: 1

MODEL:
  FUSION: parallel
  FUSION_TYPE: 1x1conv
  FUSION_CHANNEL: 

  LOAD_MODULE: pretrain/pwcnet-chairs.pth
  FREEZE_MODULE: false
  DROPOUT: 0.0

  ALT_CORR: false

CRITERION:
  VAL_DATASET: ['chairs', 'sintel', 'kitti']

OPTIMIZER:
  LR: 0.0001
  WEIGHT_DECAY: 0.00001
  EPSILON: 0.00000001


SCHEDULER:
  LR: 0.0001


