GLOBAL:
  NAME: pwcnet-things
  MIXED_PRECISION: false

  SEED: 1234
  CUDNN_ENABLED: true
  ALLOW_TF32: true
  NUM_THREADS: 16
  NUM_WORKERS: 16


TRAIN:
  STAGE: things
  RESTORE_CHECKPOINT:
  ADD_NOISE: true

  NUM_STEPS: 500000
  BATCH_SIZE: 4
  IMAGE_SIZE: [384, 768]

  SEPARATE_LR: false

  LOSS_TYPE: EPELoss
  MASK_TYPE: orb

  CLIP: 1.0

  LOSS_MODE: pretrain
  LOSS_WEIGHTS: [0.005, 0.01, 0.02, 0.08, 0.32]
  LOSS_Q:
  LOSS_EPSILON:

MODEL:
  FUSION:
  FUSION_CHANNEL: 64

  ITERS: 12
  DROPOUT: 0.0

  ALT_CORR: false

CRITERION:
  VAL_DATASET: ['chairs', 'sintel']

OPTIMIZER:
  LR: 0.0001
  WEIGHT_DECAY: 0.0004
  EPSILON: 0.00000001


SCHEDULER:
  LR: 0.0001


